### ISSUE TITLE
fork到底是深拷贝还是浅拷贝 | LIANGYUE'S BLOG

### ISSUE THREAD

**Issue by cornorghost** [cornorghost/blogcomments#138]
https://www.openrad.ink/2021/08/18/fork%E5%88%B0%E5%BA%95%E6%98%AF%E6%B7%B1%E6%8B%B7%E8%B4%9D%E8%BF%98%E6%98%AF%E6%B5%85%E6%8B%B7%E8%B4%9D/

**Comment by yangxiaoshang** [comment]
很有用，很有参考价值
